name: test script
on: 
  push:
    branches:
      actions
jobs:
   Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          job-summary: true
          custom-arguments: '-m'
          report-title: 'Test Report'
        
