name: test script
on: 
  push:
    branches:
      actions
jobs:
   Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: pip
        run: pip3 install pytest
      - name: run
        run: python -m pytest
        
