name: test script
on: 
  push:
    branches:
      test
jobs:
   Build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
    
      - name: pip
        run: |
          pip3 install pytest
          pip3 install moto
          pip3 install -r ./apiapp/requirements.txt

      - name: Run pytest
        run: |
          pip install pytest pytest-cov
          py -m venv test --doctest-modules --cov=com --cov-report=xml --cov-report=html
        # py -m venv pytest test
         
