name: test script
on: 
  push:
    branches:
      test
jobs:
   Build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
    
      - name: pip
        run: |
          pip3 install pytest
          pip3 install moto
          pip3 install -r ./apiapp/requirements.txt

      - name: Run pytest
        run: |
          pip install pytest pytest-cov
          pytest test --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
        # py -m venv pytest test
         
