name: test script
on: 
  push:
    branches:
      test
jobs:
   Build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: pip
        run: |
          pip3 install pytest          
      - name: Run pytest
        run: python -m pytest ${{ github.workspace }}\test
         
